language: cpp
dist: Xenial
services:
        - xvfb
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.2-xenial'
    update: true
    packages:
        - qt512-meta-full
        - qt512base
        - qt512tools
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
env:
  global: RUNNER="non-interactive-qt-installer/qt_installer.sh"
before_install: 
install:
- qmake --version
- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
script:
- /opt/qt512/bin/qt512-env.sh
- /opt/qt512/bin/qmake --version
- /opt/qt512/bin/qmake
- make -j$(nproc)
- "${TRAVIS_BUILD_DIR}/linuxdeployqt-continuous-x86_64.AppImage ${TRAVIS_BUILD_DIR}/partkeeprTools.desktop -verbose=1 -appimage -qmake=/opt/qt512/bin/qmake"
- mv partkeeprTools*.AppImage partkeeprTools.AppImage

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IPKAU87j48P98splVSNTPJ0v/aEcKiKbJW4pgt6ouL/6lovi22P1ALjd2JLHNMj1YZAXR+bjFlPMzLLloroKR6Fs77ZuxDaXUXSG6K7BCKvctfq02rCDBwRnVGhBcVjoYReuC6G1nEljiwAL95Bve5Hg9QWP7TCtgPKHgBNngfacNgfdpSPOcakgYaDKqbBjARxvBBKzGvwFG9gjTy9KVM263pj3UOW7RobMbydtyIdAFqD1AIRYfOdAh673tdZrZPAyjlf75xth906iQHBbVdTGGPiX1dTTgo0iJFy4pM2NOf/4D26pODpToJdROSqKqPmww0zygF+ecZ1VWxVs3pFbQOTEGiKwDF7L8gDlrYN0XU12amysV2y4+emMe8C9DJDv+b5+JulyLBf4GELgBmzrqkJJN1Qz6352pbz4vxn0fPqGDAmnzWX1g9qrpQ0/irl5eIi63N7ZD1subgbdViQ3iIwprGnNZZKsxkrNl9PGYM/oxN2qzVZ4vq5kJ/QEsoHFk/YbGzNyvqtpa+uNxeKwEt6ZoF6ov2smJFRMfPL4O2fEdcZYkfu1KTtJfM7O4mLIaCcWHtDkW4uNqmjprNtDOmtrx7JtiJNsQdg9qmDfniXGvsENzvaMKrId1pDGxy3u85dE7gs32cEBTCMOtGFHllHoenHFE7KruaXJhMg=
  file: partkeeprTools.AppImage
  on:
    tags: true

matrix:
  include:
  - os: linux
    dist: Xenial
    env:
    - PATH="/opt/qt512/bin:${PATH}"
